// src/data.js
import img1 from './assets/images/slide-img-1.jpg';
import img2 from './assets/images/slide-img-2.jpg';
import img3 from './assets/images/slide-img-3.jpg';
import img4 from './assets/images/slide-img-4.jpg';

export default [
  {
    id: 1,
    title: 'Chocolate Chip Cookies',
    cuisine: 'American',
    tags: ['dessert', 'baking', 'sweet'],
    servings: 24,
    time: { prep: 15, cook: 12, total: 27 },
    img: { src: img1, alt: 'Freshly baked chocolate chip cookies' },
    ingredients: [
      '2 1/4 cups flour',
      '1 tsp baking soda',
      '1 tsp salt',
      '1 cup butter, softened',
      '3/4 cup sugar',
      '3/4 cup brown sugar',
      '2 eggs',
      '2 tsp vanilla',
      '2 cups chocolate chips',
    ],
    steps: [
      'Preheat oven to 375°F (190°C).',
      'Cream butter and sugars until fluffy, then add eggs and vanilla.',
      'Mix in dry ingredients, then fold in chocolate chips.',
      'Drop spoonfuls on a baking sheet and bake 9–12 minutes.',
    ],
    notes: 'For softer cookies, slightly underbake.',
    dateAdded: '2025-09-13',
  },
  {
    id: 2,
    title: 'Classic Iced Coffee',
    cuisine: 'International',
    tags: ['drink', 'coffee', 'refreshing'],
    servings: 1,
    time: { prep: 5, cook: 0, total: 5 },
    img: { src: img2, alt: 'Glass of iced coffee with ice cubes' },
    ingredients: [
      '1 cup brewed coffee, cooled',
      'Ice cubes',
      '1/4 cup milk or cream',
      '1 tsp sugar or syrup (optional)',
    ],
    steps: [
      'Fill a tall glass with ice.',
      'Pour cooled coffee over the ice.',
      'Add milk or cream, then sweeten if desired.',
      'Stir and enjoy!',
    ],
    notes: 'Try flavored syrups for variety.',
    dateAdded: '2025-09-13',
  },
  {
    id: 3,
    title: 'Oatmeal Raisin Cookies',
    cuisine: 'American',
    tags: ['dessert', 'baking', 'comfort food'],
    servings: 24,
    time: { prep: 15, cook: 10, total: 25 },
    img: { src: img3, alt: 'Plate of oatmeal raisin cookies' },
    ingredients: [
      '1 cup butter, softened',
      '1 cup brown sugar',
      '2 eggs',
      '1 tsp vanilla',
      '1 1/2 cups flour',
      '1 tsp baking soda',
      '1 tsp cinnamon',
      '3 cups oats',
      '1 cup raisins',
    ],
    steps: [
      'Preheat oven to 350°F (175°C).',
      'Cream butter and sugar; add eggs and vanilla.',
      'Mix dry ingredients separately, then combine with wet ingredients.',
      'Stir in oats and raisins, drop spoonfuls on baking sheet, bake 8–10 min.',
    ],
    notes: 'Add walnuts for crunch.',
    dateAdded: '2025-09-13',
  },
  {
    id: 4,
    title: 'Cappuccino',
    cuisine: 'Italian',
    tags: ['coffee', 'hot drink', 'cafe-style'],
    servings: 1,
    time: { prep: 5, cook: 5, total: 10 },
    img: { src: img4, alt: 'Cup of cappuccino with foam art' },
    ingredients: [
      '1 shot espresso',
      '1/3 cup steamed milk',
      '1/3 cup milk foam',
    ],
    steps: [
      'Pull a fresh espresso shot into a cup.',
      'Steam milk until hot and slightly frothy.',
      'Pour steamed milk into espresso, holding back foam with a spoon.',
      'Top with milk foam and optional cocoa powder.',
    ],
    notes: 'Practice your latte art with the foam!',
    dateAdded: '2025-09-13',
  },
];
